### PR TITLE
Added Bitcoin category + book

### PR DESCRIPTION
**Pull request by sjaakvandenberg**
Hi guys, I added a free book in the Bitcoin category. It's the number one book on Amazon in the category and is specifically written for developers.

### CODE REVIEW

**Comment by caio-ribeiro-pereira** [comment]
I'm sorry, but where is the link for free ebook download? Because in the github url there are 3 publishers link but you need to pay for the book. If you have a legally link for free download update your pull request

**Comment by sjaakvandenberg** [comment]
Ebook versions and hard- and softcovers of the book can be purchased through O'Reilly and Amazon, but the entire book is available to read online in the Github repo (https://github.com/aantonop/bitcoinbook). A number of other books on your website follow this same model (JavaScript Allongé, CoffeeScript Ristretto, JavaScript Spessore, etc).

**Comment by caio-ribeiro-pereira** [comment]
Sorry, I didn't look the github files, so this book is available to read online.

**Comment by sjaakvandenberg** [comment]
Awesome, and thanks for doing this, very nice project! :)

**Comment by caio-ribeiro-pereira** [comment]
You're welcome and feel free to find and add more book, screencasts (http://devfreecasts.org) and next week I'll release a new project which lists developers communities, foruns and groups around the world (https://github.com/caio-ribeiro-pereira/devgroups) you can help me add communities if you want it.
Thanks!

**Pull request merged**
